spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zntk2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
  thymeleaf:
    cache: false
    prefix: classpath:static/templates/ 
  mvc:
    static-path-pattern: /**
  mail:
    host: smtp.qq.com
    username: 1037426886@qq.com
    password: plmxrbbmedksbfdi
    default-encoding: utf-8
    port: 456
    properties:
      mail: 
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.znck.entity
  
server:
  servlet:
    context-path: /znck

logging:
  level:
     com.znck.mapper: debug